Repository alexfalkowski/nonnative, pull requests merged in 2020-07, with the labels that each got.

#37 fix(http): allow multiple web servers
  Gemfile.lock
  README.md
  features/support/health.rb
  features/support/hello.rb
  features/support/http_server.rb
  features/support/metrics.rb
  lib/nonnative.rb
  lib/nonnative/application.rb
  lib/nonnative/grpc_server.rb
  lib/nonnative/http_server.rb
  lib/nonnative/service.rb
  nonnative.gemspec
Labels: bug

#38 feat: better http and grpc handling
  Gemfile.lock
  lib/nonnative.rb
  lib/nonnative/grpc_server.rb
  lib/nonnative/http_server.rb
  lib/nonnative/service.rb
  lib/nonnative/version.rb
  nonnative.gemspec
Labels: enhancement

#39 fix(grpc): make servers consistent
  Gemfile.lock
  README.md
  features/support/grpc_server.rb
  lib/nonnative/grpc_server.rb
  lib/nonnative/version.rb
Labels: bug

#40 bug: start servers first
  .rubocop.yml
  Gemfile.lock
  Makefile
  features/step_definitions/servers_steps.rb
  lib/nonnative/chaos_proxy.rb
  lib/nonnative/pool.rb
  lib/nonnative/version.rb
Labels: bug

#41 feat: process start and stop in order
  Gemfile.lock
  lib/nonnative/pool.rb
  lib/nonnative/version.rb
Labels: enhancement

#42 feat: add ability to create chaos
  Gemfile.lock
  features/servers.feature
  features/step_definitions/servers_steps.rb
  lib/nonnative.rb
  lib/nonnative/chaos_proxy.rb
  lib/nonnative/pool.rb
  lib/nonnative/server.rb
  nonnative.gemspec
Labels: enhancement

#43 fix: sync state
  lib/nonnative/chaos_proxy.rb
Labels: bug

#44 refactor(proxy): make consistent
  .rubocop.yml
  README.md
  features/step_definitions/servers_steps.rb
  lib/nonnative/configuration.rb
  lib/nonnative/configuration_server.rb
Labels: enhancement

#45 feat: update grpc (1.30.1)
  .rubocop.yml
  Gemfile.lock
  lib/nonnative/configuration.rb
  lib/nonnative/configuration_process.rb
  lib/nonnative/configuration_proxy.rb
  lib/nonnative/configuration_server.rb
  lib/nonnative/version.rb
  nonnative.gemspec
Labels: enhancement

#46 test: catch standard error
  features/step_definitions/servers_steps.rb
Labels: bug

#47 feat: loosen grc dep
  Gemfile.lock
  lib/nonnative/version.rb
  nonnative.gemspec
Labels: enhancement

#48 feat: loosen grc dep
  Gemfile.lock
  nonnative.gemspec
Labels: enhancement

#49 feat: update cucumber (4.1.0)
  Gemfile.lock
  Makefile
  lib/nonnative/version.rb
  nonnative.gemspec
Labels: enhancement

#50 feat: create chaos for servers
  Gemfile.lock
  features/servers.feature
  features/step_definitions/servers_steps.rb
  features/support/http_client.rb
  lib/nonnative.rb
  lib/nonnative/chaos_proxy.rb
  lib/nonnative/close_all_socket_pair.rb
  lib/nonnative/delay_socket_pair.rb
  lib/nonnative/http_client.rb
  lib/nonnative/invalid_data_socket_pair.rb
  lib/nonnative/proxy.rb
  lib/nonnative/socket_pair.rb
  lib/nonnative/socket_pair_factory.rb
  lib/nonnative/version.rb
Labels: enhancement

#51 docs: add fault injection
  README.md
Labels: documentation

#52 feat: pass options to socket pair
  .rubocop.yml
  Gemfile.lock
  README.md
  features/step_definitions/servers_steps.rb
  lib/nonnative/chaos_proxy.rb
  lib/nonnative/configuration.rb
  lib/nonnative/configuration_proxy.rb
  lib/nonnative/configuration_server.rb
  lib/nonnative/delay_socket_pair.rb
  lib/nonnative/socket_pair.rb
  lib/nonnative/version.rb
Labels: enhancement

#53 feat: add logging to servers
  .rubocop.yml
  Gemfile.lock
  README.md
  features/processes.feature
  features/processes.yml
  features/servers.feature
  features/servers.yml
  features/step_definitions/processes_steps.rb
  features/step_definitions/servers_steps.rb
  features/support/http_server.rb
  lib/nonnative/command.rb
  lib/nonnative/configuration.rb
  lib/nonnative/configuration_process.rb
  lib/nonnative/configuration_server.rb
  lib/nonnative/grpc_server.rb
  lib/nonnative/http_server.rb
  lib/nonnative/version.rb
Labels: enhancement

#54 docs: add log for servers
  README.md
Labels: documentation

#55 feat: rename proxy
  README.md
  features/servers.yml
  features/step_definitions/servers_steps.rb
  lib/nonnative.rb
  lib/nonnative/fault_injection_proxy.rb
  lib/nonnative/proxy_factory.rb
Labels: documentation, enhancement

#56 feat: add proxy logs
  Gemfile.lock
  README.md
  features/servers.yml
  features/step_definitions/servers_steps.rb
  lib/nonnative/configuration.rb
  lib/nonnative/configuration_proxy.rb
  lib/nonnative/configuration_server.rb
  lib/nonnative/fault_injection_proxy.rb
  lib/nonnative/proxy_factory.rb
  lib/nonnative/socket_pair.rb
  lib/nonnative/socket_pair_factory.rb
  lib/nonnative/version.rb
Labels: enhancement

#57 test: grpc faults
  features/servers.feature
  features/step_definitions/servers_steps.rb
Labels: enhancement

#58 feat: update to ruby-2.7.1
  .circleci/config.yml
  .rubocop.yml
  .ruby-version
  Gemfile.lock
  lib/nonnative.rb
  lib/nonnative/pool.rb
  nonnative.gemspec
Labels: enhancement

#59 refactor: remove wait
  lib/nonnative/pool.rb
Labels: enhancement

#60 build: bump to version 1.27.0
  Gemfile.lock
  lib/nonnative/version.rb
Labels: enhancement
